### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by snoyberg** [snapframework/heist#95] opened 2016-10-11 06:26 UTC
```
  heist/fsLoad: [OK]
  heist/renderNoName: [OK]
  heist/doctype: [OK]
  heist/attributeSubstitution: [OK]
  heist/bindAttribute: [OK]
  heist/markdown: [OK]
  heist/pandoc: [Failed]
ERROR: user error (Pattern match failure in do expression at test/suite/Heist/Interpreted/Tests.hs:319:9-21)
  heist/pandoc_div: [Failed]
ERROR: user error (Pattern match failure in do expression at test/suite/Heist/Interpreted/Tests.hs:319:9-21)
  heist/title_expansion: [OK]
  heist/textarea_expansion: [OK]
  heist/div_expansion: [OK]
  heist/bind_param: [OK]
  heist/markdownText: [OK]
  heist/apply: [OK]
  heist/ignore: [OK]
  heist/lookupTemplateContext: [OK]
  heist/attrSpliceContext: [OK]
  heist/json/values: [OK]
  heist/json/object: [OK]
  heist/renderXML: [Failed]
ERROR: user error (Pattern match failure in do expression at test/suite/Heist/Interpreted/Tests.hs:319:9-21)
Heist.Compiled.Tests:
  compiled/simple: [OK]
  compiled/people: [OK]
  compiled/namespace1: [Failed]
namespace test 1
expected: Right "Alpha\naoeu\nBeta\n<h:foo aoeu='htns'>Inside h:foo</h:foo>\nEnd\n"
 but got: Left ["Error rendering"]
  compiled/namespace2: [Failed]
namespace test 2
expected: Right "Alpha\naoeu\nBeta\n<h:foo aoeu='htns'>Inside h:foo</h:foo>\nEnd\n"
 but got: Left ["Error rendering"]
  compiled/namespace3: [Failed]
```

**Comment by mightybyte** [comment] 2016-10-28 09:08
Couldn't reproduce.  Not sure if it got fixed in the course of the latest release.

**Closed by mightybyte** 2016-10-28 09:08 UTC
