### ISSUE TITLE
href="" gets turned into href (="" goes away)

### ISSUE THREAD

**Issue by snap9** [snapframework/heist#104] opened 2017-05-17 16:38 UTC
This Heist code

    <a href="" onclick="return false;" id="abt">About</a>

turns into this HTML

    <a href onclick='return false;' id='abt'>About</a>

This is not good, because the W3 Validator spits out a warning about it:

    Warning: Attribute href without an explicit value seen. The attribute may be dropped by IE7.

I want my HTML to pass all validations.

Can you make `=""` not disappear?

**Comment by mightybyte** [comment] 2017-05-18 01:56
Hmmm, this is probably something to do with the xmlhtml library.  It tries to conform to the spec pretty closely.  I don't recall off the top of my head what the rules are for this.

**Comment by cdsmith** [comment] 2017-05-18 03:07
Okay, here's the situation.  Semantically, an attribute with no equal sign is equivalent to the same attribute with a quoted empty string as the value.  So we really don't want to distinguish between the two cases in the parsed document tree.  By design, the parsed document contains only the essential semantic document, and is amenable to easy pattern matching, so adding side data like this is undesirable.

Browser compatibility is a different matter, though.  There are some attributes which are expected by older browsers to NOT have the equal sign, so rendering them with an equal sign and a quoted empty string would break things.  Apparently, there are attributes on the other side, as well (including `href`).  So there's no consistent rendering 

The consistent solution would be to add information in `Text.XmlHtml.HTML.Meta` about which tags and attributes fall in which categories, and use that information when choosing how to render attributes in `Text.XmlHtml.HTML.Render`.  What makes this tricky, though, is not having a great official source for which cases need to be decided in one or the other direction.  Is the rule set for this validator available somewhere?  Might be a good start.

**Comment by snap9** [comment] 2017-05-18 10:44
@mightybyte @cdsmith 

Would it be possible to add a "leave alone" feature to Heist? This would give the user a total control over the outputted HTML when they really want it. Example:

    <heistLeaveAlone a href="" onclick="return false;" id="abt">About</a>
    
That's probably a silly way to do it, but you see what I'm getting at.

**Comment by cdsmith** [comment] 2017-05-18 16:06
How would that be represented in the parsed document type?  What would the code look like for splices that manipulate it?  And then everyone is responsible themselves for rules that are best practices for all HTML?

Seems better to just fix it for everyone.  I can implement this example easily.  I was just looking for something more complete to solve the whole problem.

**Comment by snap9** [comment] 2017-05-19 07:26
>Seems better to just fix it for everyone.

Thanks @cdsmith. I think you're right. I'm personally not aware of a more complete solution. Maybe these things could be hardcoded as they are reported (only `href` at the moment), until a more general solution is found.

**Comment by cdsmith** [comment] 2017-05-19 08:02
I've committed the change to xmlhtml.  However, I haven't been involved in Snap for many years, so you'll have to ask a current maintainer to release a new version.

**Comment by mightybyte** [comment] 2017-05-19 10:41
I just uploaded the new xmlhtml to hackage.  If you do a `cabal update` and reinstall heist, you should automatically get the new version.

**Closed** 2017-05-19 10:41 UTC

**Comment by snap9** [comment] 2017-05-23 06:05
@cdsmith @mightybyte This works great now. Thank you for the swift response!
