### ISSUE TITLE
Mock out pandoc in the test suite if the executable doesn't exist

### ISSUE THREAD

**Issue by pjones** [snapframework/heist#98] opened 2016-12-01 21:18 UTC
Is there a reason pandoc isn't listed as a dependency?

This is causing `heist` builds to fail over in [nixpkgs](https://github.com/nixos/nixpkgs).  Without an official dependency on pandoc, `cabal2nix` doesn't correctly set up an environment so heist tests can run.

I decided to open this issue instead of going directly for a PR so we can discuss the correct fix.

**Comment by imalsogreg** [comment] 2016-12-01 22:24
Seems to be some work on this here: https://github.com/NixOS/nixpkgs/pull/20832

**Comment by pjones** [comment] 2016-12-01 22:27
I think that PR is likely to be rejected since the file being changed is auto-generated (AFAIK).

I still think this is an issue with Heist.

**Comment by mightybyte** [comment] 2016-12-01 23:12
@pjones Yes, Pandoc has a GPL license.  Since we chose the BSD license for Heist we do not want to depend on pandoc directly.  So we rely on the pandoc binary being installed on your system already.

**Comment by pjones** [comment] 2016-12-01 23:33
BTW, I don't think there are any licensing issues if you add pandoc as a runtime dependency (as opposed to a build dependency).

**Comment by mightybyte** [comment] 2016-12-02 02:40
@pjones I don't understand.  What do you mean by "runtime dependency"?

**Comment by sopvop** [comment] 2016-12-02 12:14
Currently there is no way to specify tool dependencies in cabal file.
Also you don't want to add pandoc as a dependency in nix because pandoc has huge 2.5G closure, even if statically linked.

Correct fix would be either to use `findExecutable` from `directory` package to find pandoc in `PATH` and skip those tests if there is none.
Or add this to something like this to `/pkgs/development/haskell-modules/configuration-common.nix`
```nix
{
heist = addBuildTools super.heist [pkgs.pandoc]; # will only depend during build
heist = dontCheck super.heist; # turn off tests, bad idea
}
```

**Comment by pjones** [comment] 2016-12-02 15:30
@mightybyte I'm sorry, I misspoke.  I shouldn't have used the term "runtime".

Cabal does offer the `build-tools` option for specifying tools that need to be built and available for building your package.  Listing pandoc in `build-tools` under the test target would instruct Cabal to download and build pandoc as an executable and not a library.  And since Heist doesn't link with pandoc, I don't see how there can be any licensing issues.

Heist has an external dependency that is needed for the tests to pass.  At the very least it should be mocked out.  For example, why not cache the output of the real pandoc in a `test/data` folder and then write a fake pandoc script that outputs the cache to STDOUT?  In other words, what are the tests actually testing, that Heist can run an executable or that pandoc produces the correct output?

**Comment by hvr** [comment] 2016-12-02 17:43
@pjones the problem is  `build-tools` semantically refers to executable names, and for that cabal would need to know the mapping between executable name and its package name. And well, `cabal` only knows about about a dozen well-known tools (e.g. happy, alex, hsc2hs, cpphs, etc) and will download and build them (with `cabal new-build`), but we have no principled good scheme to support `build-tools` other than that (i.e. `pandoc` is not one of those). IOW, adding `pandoc` to `build-tools` won't help much, other than having `cabal` complain earlier.

However, there is gonna be a new `tool-depends` directive in future cabal versions (there's already a PR for it), which will allow to specify any package which to download, and for which to request its `exe` targets, and have it placed in `$PATH` during build; see https://github.com/haskell/cabal/issues/3708 for more details.

**Comment by pjones** [comment] 2016-12-02 17:48
@hvr Ah, that makes sense.  Thanks for the good info.

For Heist I still think that mocking out the pandoc executable would be the way to go.

**Comment by mightybyte** [comment] 2016-12-03 20:47
@pjones Yeah, I agree.  I'll reopen this and retitle appropriately.  Would love a PR if you're willing to work on it.

**Comment by pjones** [comment] 2016-12-05 17:11
Unfortunately I don't use Heist.  I stumbled upon this issue installing Snap, which brings in Heist as a dependency.  So I'm probably not the best person to work on this.

**Comment by imalsogreg** [comment] 2016-12-05 17:22
For nix users, this is fixed by https://github.com/NixOS/nixpkgs/commit/b6fe3994be79e6edf91c1c405f13182ef35bfa02

My two cents about whether this is a Heist issue or a nixpkgs issue - I suppose it comes down to how many package managers run the test suite of the package in a way that either impacts users (e.g. in in nix, running it on every user's machine and ending the build if it fails) or would be undesirable for the package maintainer to annotate by hand? Nix seems uniquely strict here, so it seems ok to have a nixpkgs-based solution. Of course when we get `tool-depends` (and cabal2nix is aware of it) that would be the ideal solution.

**Comment by mightybyte** [comment] 2018-04-09 06:02
I ended up completely removing the command line arguments heist was supplying to pandoc.  This makes it compatible with both 1.x and 2.x.  As @imalsogreg pointed out above, nixpkgs has also been fixed now, so I'm closing this issue.  Travis seems to be having network connectivity problems at the moment.  I'll release a new version to hackage after CI is working again.

**Closed by mightybyte** 2018-04-09 06:02 UTC
